services:
  app:
    build: .
    ports:
      - 5001:5000
    environment:
      ES_HOST: elasticsearch
      ES_PORT: 9200
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

volumes:
  esdata1:
